fix: use of the latest version of hatchling (#18)
to avoid the following issue:

```console
> rye publish
Uploading distributions to https://upload.pypi.org/legacy/                                   
ERROR    InvalidDistribution: Metadata is missing required fields: Name, Version.
         Make sure the distribution includes the files where those fields are specified, and 
         is using a supported Metadata-Version: 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.3.
error: failed to publish files
```